config/routes.rb
Radiodessinee::Application.routes.draw do
  resources :soirees

   root :to => 'soirees#index'

end

app/models/soiree.rb
class Soiree < ActiveRecord::Base
  attr_accessible :titre,:soundcloud_embed

  attr_accessible :affiche
  has_attached_file :affiche, :styles => {:medium => "210x297>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/soirees_controller.rb
class SoireesController < ApplicationController
  # GET /soirees
  # GET /soirees.json
  def index
    @soirees = Soiree.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @soirees }
    end
  end

  # GET /soirees/1
  # GET /soirees/1.json
  def show
    @soiree = Soiree.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @soiree }
    end
  end

  # GET /soirees/new
  # GET /soirees/new.json
  def new
    @soiree = Soiree.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @soiree }
    end
  end

  # GET /soirees/1/edit
  def edit
    @soiree = Soiree.find(params[:id])
  end

  # POST /soirees
  # POST /soirees.json
  def create
    @soiree = Soiree.new(params[:soiree])

    respond_to do |format|
      if @soiree.save
        format.html { redirect_to @soiree, notice: 'Soiree was successfully created.' }
        format.json { render json: @soiree, status: :created, location: @soiree }
      else
        format.html { render action: "new" }
        format.json { render json: @soiree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /soirees/1
  # PUT /soirees/1.json
  def update
    @soiree = Soiree.find(params[:id])

    respond_to do |format|
      if @soiree.update_attributes(params[:soiree])
        format.html { redirect_to @soiree, notice: 'Soiree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @soiree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soirees/1
  # DELETE /soirees/1.json
  def destroy
    @soiree = Soiree.find(params[:id])
    @soiree.destroy

    respond_to do |format|
      format.html { redirect_to soirees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/soirees_helper.rb
module SoireesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Radiodessinee" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Radiodessinee</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/soirees/_form.html.erb
<%= form_for @soiree, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :titre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :soundcloud_embed, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :soundcloud_embed, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
<%= f.file_field :affiche %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                soirees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/soirees/edit.html.erb
<%- model_class = Soiree -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/soirees/index.html.erb
<%- model_class = Soiree -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titre) %></th>
      <th><%= model_class.human_attribute_name(:soundcloud_embed) %></th>
      <th><%= model_class.human_attribute_name(:affiche_file_name) %></th>
      <th><%= model_class.human_attribute_name(:affiche_content_type) %></th>
      <th><%= model_class.human_attribute_name(:affiche_file_size) %></th>
      <th><%= model_class.human_attribute_name(:affiche_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @soirees.each do |soiree| %>
      <tr>
        <td><%= link_to soiree.id, soiree_path(soiree) %></td>
        <td><%= soiree.titre %></td>
        <td><%= soiree.soundcloud_embed %></td>
        <td><%= soiree.affiche_file_name %></td>
        <td><%= soiree.affiche_content_type %></td>
        <td><%= soiree.affiche_file_size %></td>
        <td><%= soiree.affiche_updated_at %></td>
        <td><%=l soiree.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_soiree_path(soiree), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      soiree_path(soiree),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_soiree_path,
            :class => 'btn btn-primary' %>

app/views/soirees/new.html.erb
<%- model_class = Soiree -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/soirees/show.html.erb
<%- model_class = Soiree -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<%= image_tag @soiree.affiche.url(:medium) %>

<%= raw @soiree.soundcloud_embed %>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              soirees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_soiree_path(@soiree), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              soiree_path(@soiree),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>